baseURL = "https://rh-telco-tigers.github.io/"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "Red Hat Telco Tigers Repository"
disqusShortname = "disqus-code"
googleAnalytics = "analytics-code"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "A description for the meta tag of the site"
    googleSearch = "google-search-code"
    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page
    githubLink = "rafed/ramium/"

    tagsInHome = 0     # set zero to not show in home page
    sectionsInHome = 5  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

#    [[menu.main]]
#        identifier = "blog"
#        name = "This Blog"
#        weight = 2
#            [[menu.main]]
#                parent = "blog"
#                name = "All Tags"
#                url = "/tags/"
#                weight = 1
#            [[menu.main]]
#                parent = "blog"
#                name = "All Sections"
#                url = "/sections/"
#                weight = 2
#            [[menu.main]]
#                parent = "blog"
#                name = "All Posts"
#                url = "/posts/"
#                weight = 3
    
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 3
